shoop:
  getURL: http://dax.sveetch.net/tribune/remote.xml
  postURL: http://dax.sveetch.net/tribune/post.xml
  lastIdParameter: last
  postParameter: content
  alias: "sveetch,dax"

euromussels:
  getURL: http://euromussels.eu/?q=tribune.xml
  postURL: http://euromussels.eu/?q=tribune/post
  lastIdParameter: last_id
  postParameter: message
